<<<<<<< HEAD
# Generated by Django 5.2.4 on 2025-07-16 20:42
=======
# Generated by Django 5.2.4 on 2025-07-16 20:50
>>>>>>> 649eebc80a0902f0d72e615f6cbda367670f6a24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('idVenta', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('paisVenta', models.CharField(max_length=100)),
                ('estadoVenta', models.CharField(max_length=100)),
                ('ciudadVenta', models.CharField(max_length=200)),
                ('unidad', models.CharField(max_length=20)),
                ('vendedor', models.CharField(max_length=200)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventasCliente', to='clientes.clientes')),
            ],
        ),
    ]
