# Generated by Django 5.2.4 on 2025-07-10 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ventas",
            fields=[
                (
                    "idVenta",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("fecha", models.DateTimeField()),
                ("paisVenta", models.CharField(max_length=100)),
                ("estadoVenta", models.CharField(max_length=100)),
                ("ciudadVenta", models.CharField(max_length=200)),
                ("unidad", models.CharField(max_length=20)),
                ("vendedor", models.CharField(max_length=200)),
                ("total", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "idCliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ventasCliente",
                        to="clientes.clientes",
                    ),
                ),
            ],
        ),
    ]
