<<<<<<< HEAD
# Generated by Django 5.2.4 on 2025-07-16 20:42
=======
# Generated by Django 5.2.4 on 2025-07-16 20:50
>>>>>>> 649eebc80a0902f0d72e615f6cbda367670f6a24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumos',
            fields=[
<<<<<<< HEAD
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("sku", models.CharField(max_length=15)),
                ("marca", models.CharField(default="", max_length=150)),
                ("maxActual", models.IntegerField()),
                ("minActual", models.IntegerField()),
                ("existenciaActual", models.IntegerField(default=0)),
                ("categoria", models.CharField(default="", max_length=150)),
                ("proveedor", models.CharField(default="", max_length=200)),
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=15)),
                ('marca', models.CharField(default='', max_length=150)),
                ('maxActual', models.IntegerField()),
                ('minActual', models.IntegerField()),
                ('existenciaActual', models.IntegerField(default=0)),
                ('categoria', models.CharField(default='', max_length=150)),
                ('proveedor', models.CharField(default='', max_length=200)),
>>>>>>> 649eebc80a0902f0d72e615f6cbda367670f6a24
            ],
        ),
    ]
