# Generated by Django 5.2.4 on 2025-07-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumos',
            name='existenciaActual',
            field=models.IntegerField(default=0),
        ),
    ]
