# Generated by Django 5.2.4 on 2025-07-16 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0002_insumos_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumos',
            name='tipoInsumo',
        ),
    ]
