# Generated by Django 5.2.4 on 2025-07-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0003_insumos_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumos',
            name='categoria',
            field=models.CharField(default='', max_length=150),
        ),
    ]
