# Generated by Django 5.2.4 on 2025-07-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0004_insumos_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumos',
            name='tipoInsumo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
