# Generated by Django 5.2.4 on 2025-07-10 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("insumos", "0001_initial"),
        ("productos", "0001_initial"),
        ("ventas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VentasPV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.BigIntegerField()),
                (
                    "precioUnitario",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "idInsumo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ventasPVInsumos",
                        to="insumos.insumos",
                    ),
                ),
                (
                    "idProducto",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ventasPVProducto",
                        to="productos.productos",
                    ),
                ),
                (
                    "idVenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ventasPVVenta",
                        to="ventas.ventas",
                    ),
                ),
            ],
        ),
    ]
