<<<<<<< HEAD
# Generated by Django 5.2.4 on 2025-07-16 20:42
=======
# Generated by Django 5.2.4 on 2025-07-16 20:50
>>>>>>> 649eebc80a0902f0d72e615f6cbda367670f6a24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumos', '0001_initial'),
        ('productos', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentasPVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('cantidad', models.BigIntegerField()),
                ('idInsumo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventasPVInsumos', to='insumos.insumos')),
                ('idProducto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventasPVProducto', to='productos.productos')),
            ],
        ),
        migrations.CreateModel(
            name='VentasPVH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('cantidad', models.BigIntegerField()),
                ('precioUnitario', models.DecimalField(decimal_places=2, max_digits=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('idVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventasPVVenta', to='ventas.ventas')),
            ],
        ),
    ]
