# Generated by Django 5.2.4 on 2025-07-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventasPV", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ventaspvh",
            name="categoria",
            field=models.CharField(default="", max_length=100),
        ),
    ]
