# Generated by Django 5.2.4 on 2025-07-22 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='fechaCreacion',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
