# Generated by Django 5.2.4 on 2025-07-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_productos_existenciaactual'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='marca',
            field=models.CharField(default='', max_length=150),
        ),
    ]
