# Generated by Django 5.2.4 on 2025-07-16 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_productos_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='precio',
        ),
    ]
