# Generated by Django 5.2.4 on 2025-07-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_productos_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='tipoProducto',
            field=models.CharField(default='', max_length=100),
        ),
    ]
