# Generated by Django 5.2.4 on 2025-07-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_productos_tipoproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='precio',
            field=models.FloatField(default=0),
        ),
    ]
