# Generated by Django 5.2.4 on 2025-07-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialpi',
            name='cantidad',
            field=models.FloatField(),
        ),
    ]
