<<<<<<< HEAD
# Generated by Django 5.2.4 on 2025-07-16 20:42
=======
# Generated by Django 5.2.4 on 2025-07-16 20:50
>>>>>>> 649eebc80a0902f0d72e615f6cbda367670f6a24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idCliente', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('pais', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=200)),
                ('tipoCliente', models.CharField(default='Cliente Nuevo', max_length=20)),
                ('numTransacciones', models.BigIntegerField(default=0)),
            ],
        ),
    ]
