# Generated by Django 5.2.4 on 2025-07-21 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Caducidades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fechaCaducidad", models.DateField()),
                ("cantidad", models.IntegerField()),
                (
                    "productoId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productoCaducidad",
                        to="productos.productos",
                    ),
                ),
            ],
        ),
    ]
